onboarding = false
[ui.toast]
delivery = "herdr"

[ui]
status_indicators = "symbols"
pane_gaps = false

[keys]
prefix = "ctrl+space"
previous_workspace = "alt+up"
next_workspace = "alt+down"
previous_tab = "alt+left"
next_tab = "alt+right"
move_tab_previous = "alt+shift+left"
move_tab_next = "alt+shift+right"
split_horizontal = ["prefix+minus", "alt+shift+enter"]
split_vertical = ["prefix+v", "alt+enter"]
focus_pane_left = ["prefix+h", "ctrl+alt+left"]
focus_pane_down = ["prefix+j", "ctrl+alt+down"]
focus_pane_up = ["prefix+k", "ctrl+alt+up"]
focus_pane_right = ["prefix+l", "ctrl+alt+right"]
close_pane = ["prefix+x", "alt+esc"]

[keys.indexed]
tabs = "alt"

[theme]
name = "catppuccin"
auto_switch = false
